### ISSUE TITLE
Plot artifacts

### ISSUE THREAD

**Issue by weaverba137** [sbailey/prospect#1]
I was using prospect in standalone HTML mode and saw some odd artifacts.  Notice the faint vertical lines at about 4200 Å.  These persist when switching to other spectra, although sometimes they move around. bokeh version = 1.0.4.

![bokeh_screenshot](https://user-images.githubusercontent.com/3780690/52887971-106c3500-3137-11e9-90dc-3a68e7609f37.png)

**Comment by armengau** [comment]
Could not reproduce this (vertical lines are where they should be), with bokeh version = 0.13.0 (desi_environment 18.7)

**Comment by weaverba137** [comment]
That's fine.  I have not seen those artifacts with recent versions of Bokeh.

**Comment by weaverba137** [comment]
Closing this because it no longer appears to be an issue.
