### ISSUE TITLE
May need to optimize the viewer fluidity 

### ISSUE THREAD

**Issue by armengau** [sbailey/prospect#16]
CustomJS code could be optimized to have the viewer more reacting.
On spectrum change (ie. update_plot() function), right now **it takes around 1 sec on firefox** and even 2 sec on an old version of safari.
Surprizingly (on old safari) :
- smoothing / camera-coadding take ~100ms each (that's ok)
- modifying the "targetinfo" text Div takes 400 ms !
- zslider operations take 1.2 sec !! half of it by editing the "z_current" text Div !!

**A first action would be to replace bokeh's text Divs with a widget more adapted to changes of content **
@weaverba137  do you have any idea ?

**Comment by weaverba137** [comment]
I will think about this, but I might not get to it until next week due to observing this week.

**Comment by sbailey** [comment]
+1 for making the interface more reactive.  That was a key goal of the original Prospect, where changing targets and operations like zslider had almost no delay.  The time to update the Divs is surprising, but I wouldn't be surprised if the extra noise/sky vectors bogging things down.

**Comment by weaverba137** [comment]
@armengau , can you give an example page that has this problem?  That will let me look at the relevant JavaScript code.

**Comment by armengau** [comment]
Any html page, eg. 
https://portal.nersc.gov/project/desi/users/armengau/svdc2019c/v2/elg_targets/pix26331/specviewer_ELG_pix26331_5.html

I manually tested the speed with js commands like d=Date() and console.log(d.getTime() -t0) ..

I see 2 things to improve :
-  bokeh "Divs" seem to be non-optimal if the text inside Div changes.
Maybe try to replace the div by a DataTable (with appropriate style; must show only one row) ?
- zsliders themselves : I edited the code some time ago to handle noise, coadd, avoid duplicate code. Will have a look at that.

**Comment by weaverba137** [comment]
I notice that I didn't have to input a password to see that page.  Are we OK with the general public (theoretically) having the ability to view these pages?

**Comment by armengau** [comment]
- For mock(svdc2019)-based data I suppose it's ok
- It's probably not ok for real data (even cmx?).
@sbailey, I would like to create a dir structure in $DESI_WWW dedicated to prospect pages (not my own dir), protected by a password :
1. Do you have a suggestion for the dir structure (name? one subdir for cmx, one for mini-sv...)
2. htaccess : I am not aware of a "generic" desi password we could use ?

**Comment by weaverba137** [comment]
If you place anything in $DESI_WWW/collab, it will automatically be password-protected.

**Comment by armengau** [comment]
Div were replaced by DataTable ==> just waiting to see if users don't disagree too much.
This really makes it faster, and I could add more targeting infos.

Also slightly optimized zslider script.
So now the redshift sliders are fluid again
