### ISSUE TITLE
"Delta redshift" is somewhat counterintuitive

### ISSUE THREAD

**Issue by weaverba137** [sbailey/prospect#4]
The redshift and delta redshift sliders control the first two and second two significant figures of the redshift, respectively.  At first it looked like delta redshift did not allow for negative offsets until I figured this out.  Is there a particular reason why the redshift sliders are set up this way?

Also, there is no readout that displays the new redshift after adjusting the sliders.  It seems like this would be nice to have, rather than mentally adding, *e.g.*, 0.25 and 0.0066.  I know, it's not difficult math, but still.

**Comment by weaverba137** [comment]
PS, there probably ought to be a reset button for those sliders.

**Comment by sbailey** [comment]
+1 for a reset button, and +1 for having something in the display showing what the current redshift+delta is.

The reason for splitting these into two separate sliders was that I couldn't do fine-grained enough redshift control using a single slider while still covering a full redshift range.  Suggestions for alternative / clearer methods are welcome.  Simply displaying the current redshift+delta may make it obvious enough.

**Comment by armengau** [comment]
In the branch proto_static, the possibility to have delta_redshift<0 is included (I just thought it could be useful). No strict bug but still not very clear, should try some different presentation indeed...

**Comment by armengau** [comment]
Now I added 
- a text in the gui to show the current "displayed" z+delta
- a reset z button
- and suggest the following renaming for both sliders : "Redshift rough tuning" and "Redshift fine-tuning"

**Comment by weaverba137** [comment]
That sounds fine. Do you have a generated example to look at?

**Comment by weaverba137** [comment]
I saw your slide, & it looks very good. Closing.
