### ISSUE TITLE
Prospect in Jupyter Notebook?

### ISSUE THREAD

**Issue by weaverba137** [sbailey/prospect#6]
I have seen mention that prospect is working in a JupyterLab notebook.  Where can I find an example notebook?  Would it be possible to check in that notebook to this repository?

**Comment by weaverba137** [comment]
Actually, it turns out that *I* have a JupyterLab notebook with a working version of prospect.  It would still be interesting to compare to other working notebooks and possibly merge.

**Comment by armengau** [comment]
I had this one : ~armengau/Prospect_demo.ipynb but it's currently working with the code version available in ~armengau/prospect which is not as of now the most up-to-date

**Comment by armengau** [comment]
Example in doc/nb/Prospect_demo.ipynb
